### ISSUE TITLE
No vendor folder in node-sass at Hello World example

### ISSUE THREAD

**Issue by phoenleo** [FountainJS/generator-fountain-webapp#103]
Hi, I tried serving the default Hello-World app.
I cannot serve the webapp using `npm run serve` due to no vendor folder in downloaded node-sass.
### Error Message & Stack Trace

```
ERROR in ./~/css-loader!./~/sass-loader!./~/postcss-loader!./src/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.getInstalledBinaries (/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/node-sass/lib/extensions.js:119:13)
    at foundBinariesList (/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/touchtenmac-14/Documents/PHOEN/finance-tracker/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
 @ ./src/index.scss 4:14-158
```
## Environment
- node-sass version _3.8.0_
- generator-fountain-angular1 version _0.6.0_
  - node-sass version in package json is `"node-sass": "^3.4.2"`
## Used Technologies:
- angular1
- sass
- webpack
- plain javascript
## Solution

After searching to multiple threads, 
this issue caused by changes made from node-sass 3.4.x to higher version.
I can fix this serving issue by rebuild the node-sass using this command:

`npm rebuild node-sass`

I found the solution in this issue thread davezuko/react-redux-starter-kit#791

**Comment by micaelmbagira** [comment]
Hi @phoenleo Which versions of node/npm do you have ?

**Comment by phoenleo** [comment]
Hi @micaelmbagira,
I use node ver 6.2.2 and npm ver 3.10.6

**Comment by micaelmbagira** [comment]
Alright, I see you've found a solution. Probably something went wrong during the `npm install`...

**Comment by SpencerKaiser** [comment]
@micaelmbagira I just ran into this exact same issue as @phoenleo and his solution worked for me as well

**Comment by adeguk** [comment]
I had the same problem node-sass vendor not found each i ran "npm run dev". 
  laravel 5.4
  node 7.10.0
  npm 4.2.0

I did notice when i check node-module\node-sass that the vendor folder is missing. But after a few research online and lots of try and error, i found the simple solution is to rebuild the sass module by simply running:

> npm rebuild node-sass
> npm run dev

**Comment by surajfromleo** [comment]
I am also facing same problem from couple of days , now its done . Thanks Man
