### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by sebastianovide** [FountainJS/generator-fountain-webapp#12]
on a fresh new project

```
(18:06:05):~/dev/tests/my-new-project (master *)$ yo fountain-webapp
? Which JavaScript framework do you want? React
? Which module management do you want? Webpack with NPM
? Which CSS preprocessor do you want? CSS
? Which JS preprocessor do you want? Pure old JavaScript
? Do you want a sample app? Just a Hello World
...
...
(18:06:54):~/dev/tests/my-new-project (master)$ gulp
[18:07:08] Loading /Users/sebas/dev/tests/my-new-project/gulp_tasks/misc.js
[18:07:08] Loading /Users/sebas/dev/tests/my-new-project/gulp_tasks/browsersync.js
[18:07:08] Loading /Users/sebas/dev/tests/my-new-project/gulp_tasks/karma.js
[18:07:09] Loading /Users/sebas/dev/tests/my-new-project/gulp_tasks/webpack.js
[18:07:09] Using gulpfile ~/dev/tests/my-new-project/gulpfile.js
[18:07:09] Starting 'default'...
[18:07:09] Starting 'clean'...
[18:07:09] Finished 'clean' after 4.66 ms
[18:07:09] Starting 'build'...
[18:07:09] Starting 'other'...
[18:07:09] Starting 'webpack:dist'...
[18:07:09] Finished 'other' after 38 ms
[18:07:09] Time: 236ms

ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/sebas/dev/tests/my-new-project"
    at /Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:393:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:385:20)
    at OptionManager.mergePresets (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:10)
    at OptionManager.mergeOptions (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328:14)
    at OptionManager.addConfig (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:10)
    at OptionManager.findConfigs (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:434:16)
    at OptionManager.init (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:482:12)
    at File.initOptions (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/Users/sebas/dev/tests/my-new-project/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at transpile (/Users/sebas/dev/tests/my-new-project/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/sebas/dev/tests/my-new-project/node_modules/babel-loader/index.js:88:12)
[18:07:09] Finished 'webpack:dist' after 253 ms
[18:07:09] Finished 'build' after 260 ms
[18:07:09] Finished 'default' after 266 ms
(18:07:10):~/dev/tests/my-new-project (master)$

```

**Comment by Swiip** [comment]
There is a miss for installing https://www.npmjs.com/package/babel-preset-es2015. This should be fixed in the next release.

**Comment by zckrs** [comment]
New release `v0.4.0`
