### ISSUE TITLE
Startup failed => Angular 1 + Babel  + travis + bower + css + hello world sample 

### ISSUE THREAD

**Issue by amgadfahmi** [FountainJS/generator-fountain-webapp#144]
## Environment
- Windows 10 @latest (64)
- npm@3.10.8
- node@v4.6.0
## Description

Crashes running gulp server or npm run serve 
### Error Message & Stack Trace

```
10 verbose lifecycle @~serve: CWD: C:\Users\Amgad\Desktop\fountainJs
11 silly lifecycle @~serve: Args: [ '/d /s /c', 'gulp serve' ]
12 silly lifecycle @~serve: Returned: code: 1  signal: null
13 info lifecycle @~serve: Failed to exec serve script
14 verbose stack Error: @ serve: `gulp serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Amgad\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Amgad\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid @
16 verbose cwd C:\Users\Amgad\Desktop\fountainJs
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Amgad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
19 error node v4.6.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error @ serve: `gulp serve`
22 error Exit status 1
23 error Failed at the @ serve script 'gulp serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
### Config

Default config

**Comment by micaelmbagira** [comment]
Hi @amgadfahmi, yes that's a bug. Can you run `npm install --save-dev babel-plugin-istanbul` ?

**Comment by amgadfahmi** [comment]
Yeah that's made it work only using the following command `npm run serve` but the regular `gulp serve` is crashing with message

>  can't read property apply of undefined

**Comment by micaelmbagira** [comment]
Yes, as explained in the README, if you want to use gulp commands you need to install gulp 4 globally: npm install -g. Otherwise you can use nom commands.

**Comment by amgadfahmi** [comment]
@micaelmbagira  thanks
