### ISSUE TITLE
gulp serve failed, Angular2+Typescript+Webpack+Helloworld

### ISSUE THREAD

**Issue by ekuwang** [FountainJS/generator-fountain-webapp#157]
when I run gulp serve, it prints out:
...
...
[12:52:57] Using gulpfile ~/dev/wwwroot/qjs-web-frontend/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by ekuwang** [comment]
I know the reason...my gulp version is wrong
