### ISSUE TITLE
"File not found with singular glob error" in build with default project

### ISSUE THREAD

**Issue by tetsujin1979** [FountainJS/generator-fountain-webapp#168]
## Description

Created a new project using fountainJS, made no changes to the code, and running "gulp build" gives the error below, and running "gulp serve" displays a blank screen in a browser.

Index.html is in the C:\WorkArea\temp\fountain\.tmp\src\ directory, not C:\WorkArea\temp\fountain\.tmp\ which only contains templateCacheHtml.js

### Error Message & Stack Trace

```
[16:12:15] Error: File not found with singular glob: C:\WorkArea\temp\fountain\.tmp\index.html
    at Glob.<anonymous> (C:\WorkArea\temp\fountain\node_modules\glob-stream\index.js:41:11)
    at Glob.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (C:\WorkArea\temp\fountain\node_modules\glob-stream\node_modules\glob\glob.js:172:8)
    at done (C:\WorkArea\temp\fountain\node_modules\glob-stream\node_modules\glob\glob.js:159:12)
    at Glob._processSimple2 (C:\WorkArea\temp\fountain\node_modules\glob-stream\node_modules\glob\glob.js:652:12)
    at C:\WorkArea\temp\fountain\node_modules\glob-stream\node_modules\glob\glob.js:640:10
    at Glob._stat2 (C:\WorkArea\temp\fountain\node_modules\glob-stream\node_modules\glob\glob.js:736:12)
    at lstatcb_ (C:\WorkArea\temp\fountain\node_modules\glob-stream\node_modules\glob\glob.js:728:12)
    at RES (C:\WorkArea\temp\fountain\node_modules\inflight\inflight.js:31:16)
    at f (C:\WorkArea\temp\fountain\node_modules\once\once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:123:15)
[16:12:15] 'build' errored after 637 ms
```

### Config

Copy the content from `.yo-rc.json`:

```json
{
  "generator-fountain-angular1": {
    "version": "1.0.0-rc1",
    "props": {
      "framework": "angular1",
      "modules": "inject",
      "js": "js",
      "ci": [],
      "css": "css",
      "resolved": "C:\\Users\\developer\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-webapp\\node_modules\\generator-fountain-angular1\\generators\\app\\index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "hello",
      "router": "uirouter"
    }
  }
}
```

## Relevant Links

Project zipped and uploaded here: https://sites.google.com/site/tetsujin1979/Home/fountain.zip

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v6.9.2
win32 6.1.7601

yo --version
1.8.5

npm --version
4.0.3
```

**Comment by ahmadalfy** [comment]
Same issue here as well

**Comment by nk2580** [comment]
same issue here - only i am missing he templateCache.js file

**Comment by challet** [comment]
same for the command "gulp serve:dist"

**Comment by pixelbacon** [comment]
++

**Comment by pixelbacon** [comment]
Just like the original ticket says, this is an issue out of the box. High priority defect.

**Comment by pixelbacon** [comment]
@ahmadalfy @nk2580 @challet Remember to up-vote the original post (the thumbs up icon directly under the original post).

**Comment by AntoineMoues** [comment]
same issue here

**Comment by Paul-Perrier** [comment]
same issue

**Comment by nk2580** [comment]
This is due to your build setup attempting to find a file which doesn't exist, the easiest solution is to pull your files into a new project one by one.. or alternatively move to webpack, the bower inject template cache file is updated when you generate new files but doesn't do the same when you delete them, so it's pointing somewhere that doesn't exist. If you move to webpack you'll get a better error response so you'll be able to fix the file.
