### ISSUE TITLE
build: SystemJS is not defined

### ISSUE THREAD

**Issue by wojciechpolak** [FountainJS/generator-fountain-webapp#17]
Hello,

Testing v0.4.0.

```
? Which JavaScript framework do you want? Angular 1
? Which module management do you want? SystemJS with JSPM
? Which CSS preprocessor do you want? SASS
? Which JS preprocessor do you want? ES2015 today with Babel
? Do you want a sample app? A working landing page

$ ./node_modules/.bin/jspm install
...
ok   Install complete.

$ npm test
...
PhantomJS 2.1.1 (Linux 0.0.0): Executed 6 of 6 SUCCESS (0.086 secs / 0.058 secs)
[14:41:24] Finished 'karma:single-run' after 2.78 s
```

Then running `build` fails with SystemJS, no matter if selected above is Angular 1 or 2, ES5 or ES6. But running `npm run serve` ends successfully.

```
$ npm run build
[14:41:56] Starting 'default'...
[14:41:56] Starting 'clean'...
[14:41:56] Finished 'clean' after 6.37 ms
[14:41:56] Starting 'build'...
[14:41:56] Starting 'partials'...
[14:41:56] Finished 'partials' after 66 ms
[14:41:56] Starting 'systemjs'...
[14:41:56] Starting 'systemjs:html'...
[14:41:56] Starting 'styles'...
[14:41:56] Starting 'other'...
[14:41:56] 'systemjs' errored after 285 ms
[14:41:56] ReferenceError: SystemJS is not defined
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at Object.exports.runInNewContext (vm.js:49:17)
    at Builder.executeConfigFile (/somepath/node_modules/systemjs-builder/lib/builder.js:276:17)
    at Builder.loadConfigSync (/somepath/node_modules/systemjs-builder/lib/builder.js:286:21)
    at new Builder (/somepath/node_modules/systemjs-builder/lib/builder.js:52:10)
    at systemjs (/somepath/gulp_tasks/systemjs.js:12:19)
    at taskWrapper (/somepath/node_modules/undertaker/lib/set-task.js:13:15)
    at taskWrapper (/somepath/node_modules/undertaker/lib/set-task.js:13:15)
    at taskWrapper (/somepath/node_modules/undertaker/lib/set-task.js:13:15)
[14:41:56] 'build' errored after 352 ms
[14:41:56] 'default' errored after 361 ms
[14:41:56] The following tasks did not complete: systemjs:html, styles, other
[14:41:56] Did you forget to signal async completion?
```

After changing `SystemJS.config` to `System.config` in `jspm.config.js`, the error message changed to the following:

```
$ npm run build
...
[14:53:58] Starting 'other'...
[14:53:59] 'systemjs' errored after 473 ms
[14:53:59] Error on translate for src/index.js at file:///somepath/src/index.js
    Error: Unable to fetch "npm:systemjs-plugin-babel@0.0.8.json". Only file URLs of the form file:/// allowed running in Node.
    at fetchTextFromURL (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1071:15)
    at /somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1623:7
    at new Promise (/somepath/node_modules/karma/node_modules/core-js/modules/es6.promise.js:193:7)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1622:12)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:2543:22)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:3108:20)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:3336:18)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:3956:20)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:4147:22)
    at SystemJSNodeLoader.<anonymous> (/somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:4383:20)
    at /somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:2300:49
    at /somepath/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:2346:11
    at run (/somepath/node_modules/karma/node_modules/core-js/modules/es6.promise.js:89:22)
    at /somepath/node_modules/karma/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/somepath/node_modules/karma/node_modules/core-js/modules/_microtask.js:14:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

P.S. Using Node.js v5.10.1

**Comment by zckrs** [comment]
IMO at moment we don't support build task for SystemJS :-/

**Comment by Swiip** [comment]
It worked at one point. I wonder if it's not the upgrade to system 0.17 which broke the thing...

**Comment by micaelmbagira** [comment]
The version of `systemjs-builder` was outdated, it will be fixed in next release.

**Comment by Swiip** [comment]
released
