### ISSUE TITLE
Installation command problem

### ISSUE THREAD

**Issue by trextroy** [FountainJS/generator-fountain-webapp#185]
....\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\fountain-generator\lib\Base.js:21
    const {framework, modules, js} = this.options;
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Akash\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\fountain-generator\index.js:2:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Hi, 
I am getting above error while launching the generator after all dependencies installed properly. 
$npm install -g yo generator-fountain-webapp  ==>  this works fine with no issue. 

However I am stuck immediately while try to run the below command. 
$ yo fountain-webapp

Please help.

**Comment by Swiip** [comment]
This should come from your node version. Have you Node 6+ as required?

**Comment by trextroy** [comment]
Oh thank you so much. I am using 4.4.1. let me upgrade it.

**Comment by ErichBSchulz** [comment]
mmm... that is interesting.

This page needs updating: http://yeoman.io/codelab/setup.html

**Comment by trextroy** [comment]
I guess I missed it that time, they already mention here. 
https://github.com/FountainJS/generator-fountain-webapp

**Comment by abdallahokasha** [comment]
what happened with me that i had an old version of node and yeoman requires node v6 or higher
so i simply run:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```
and it works with me
You can check this if you have Linux OS distribution:
[https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

http://yeoman.io/codelab/setup.html
