### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by kikar** [FountainJS/generator-fountain-webapp#20]
I'm using OSX 10.11.4 with Node 5.10.1 and NPM 3.8.3

I just run the instructions:
1. `npm install -g yo gulp-cli`
2. `npm install -g generator-fountain-webapp`
3. `yo fountain-webapp`

But I get this error: 

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'mem-fs'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/fountain-generator/lib/test-utils.js:2:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by micaelmbagira** [comment]
I am going to have a look on this one. Meanwhile you can manually run `npm install mem-fs`.

**Comment by kikar** [comment]
Tried to run `npm install mem-fs` in the project folder, but didn't work.
Tried even to run `npm install -g mem-fs`, also didn't work

**Comment by micaelmbagira** [comment]
Probably you also need to install `mem-fs-editor`.

**Comment by zckrs** [comment]
```
~/github/testFountainReactTech   
❯ yo fountain-webapp
? Which JavaScript framework do you want? React
? Which module management do you want? Webpack with NPM
? Which CSS preprocessor do you want? SASS
? Which JS preprocessor do you want? ES2015 today with Babel
? Do you want a sample app? A working landing page
```

```
~/github/testFountainReactTech   26s
❯ npm ls -g --depth 0
/home/zckrs/.nvm/versions/node/v4.3.2/lib
├── bower@1.7.9
├── eslint@2.4.0
├── generator-fountain-webapp@0.4.0
├── gulp-cli@1.2.1
├── jspm@0.16.32
├── local-npm@1.5.8
├── mocha@2.4.5
├── now@0.9.19
├── npm@3.8.6
├── npm-check@5.2.1
├── pm2@1.0.2
├── selenium-standalone@5.1.0
├── typings@0.7.12
├── webpack@1.12.14
└── yo@1.7.0
```

It works :/ 

can you please paste your  npm ls -g --depth 0 @kikar

**Comment by kikar** [comment]
```
/Users/avoda/.nvm/versions/node/v5.10.1/lib
├── bower@1.7.9
├── generator-fountain-webapp@0.4.0
├── gulp@3.9.1
├── gulp-cli@1.2.1
├── mem-fs@1.1.2
├── mem-fs-editor@2.2.0
├── npm@3.8.3
└── yo@1.7.0
```

Btw @micaelmbagira, still not working even with mem-fs-editor

**Comment by micaelmbagira** [comment]
Which error do you have now ?

**Comment by zckrs** [comment]
- mem-fs and mem-fs-editor should not be in global
- gulp@3.9.1 is replaced by gulp-cli you can remove it
- after that can you run `yo doctor`

**Comment by kikar** [comment]
New npm ls: 

```
/Users/avoda/.nvm/versions/node/v5.10.1/lib
├── bower@1.7.9
├── generator-fountain-webapp@0.4.0
├── gulp-cli@1.2.1
├── npm@3.8.3
└── yo@1.7.0
```

Result from `yo doctor` is all right: 

```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
```

Error is the same as above

**Comment by zckrs** [comment]
I am on Ubuntu with the same global pacakge and node version.

```
/home/zckrs/.nvm/versions/node/v5.10.1/lib
├── generator-fountain-webapp@0.4.0
├── npm@3.8.3
└── yo@1.7.0
```

And generator works :S 

Very strange.

**Comment by zckrs** [comment]
Can you try to remove/install generator-fountain-webapp ?

**Comment by kikar** [comment]
Uninstalled and reinstalled generator-fountain-webapp and now it works 🤔

**Comment by kikar** [comment]
Trying now with Node 4.4.3 and NPM 2.15.1

Still same error after 2/3 reinstall

My `npm ls -g --depth=0`:

```
/usr/local/lib
├── bower@1.7.9
├── express-generator@4.13.1
├── generator-fountain-webapp@0.4.0
├── generator-gulp-angular@1.1.0
├── grunt-cli@0.1.13
├── gulp-cli@1.2.1
├── jshint@2.9.1
├── ngrok@0.2.2
├── nodemon@1.9.1
├── npm@2.15.1
├── speed-test@1.7.0
└── yo@1.7.0
```

**Comment by kikar** [comment]
@micaelmbagira @zckrs Just tried on another mac with same OSX, Node, and npm and still doesn't work. Please reopen the issue.

**Comment by zckrs** [comment]
IMO you have a issue when NPM download and install the package.

Can you share output of `npm i -g generator-fountain-webapp` ?

**Comment by zckrs** [comment]
I reproduce with NPM2

https://github.com/FountainJS/fountain-generator/pull/16

**Comment by zckrs** [comment]
Should be fix on next release @kikar

**Comment by kikar** [comment]
Thanks @zckrs .  In case it helps further, my output of `npm i -g generator-fountain-webapp`:

```
> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/fountain-generator/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

generator-fountain-webapp@0.4.0 /usr/local/lib/node_modules/generator-fountain-webapp
├── generator-fountain-react@0.4.0 (generator-fountain-gulp@0.4.0)
├── generator-fountain-angular2@0.4.0 (generator-fountain-gulp@0.4.0)
├── generator-fountain-angular1@0.4.0 (generator-fountain-gulp@0.4.0)
└── fountain-generator@0.4.0 (minimatch@3.0.0, ejs@2.4.1, falafel@1.2.0, lodash@4.11.1, yeoman-generator@0.22.5)
```

Also, is there any approx ETA for next release?

**Comment by zckrs** [comment]
[Project under heavy development](https://github.com/FountainJS/generator-fountain-webapp#project-under-heavy-development)

Sorry no ETA :anguished:  but the v0.5.0 should be beta version

**Comment by giksa** [comment]
I have problems too with gulp serve

```
~/V/consulta » gulp serve                                                                                                                                                                           go1.6.2
[22:13:50] Loading /Users/giksa/Varios/consulta/gulp_tasks/misc.js
[22:13:50] Loading /Users/giksa/Varios/consulta/gulp_tasks/browsersync.js
[22:13:50] Loading /Users/giksa/Varios/consulta/gulp_tasks/karma.js
[22:13:50] Loading /Users/giksa/Varios/consulta/gulp_tasks/webpack.js
[22:13:51] Using gulpfile ~/Varios/consulta/gulpfile.js
[22:13:51] Starting 'serve'...
[22:13:51] Starting 'webpack:watch'...
ts-loader: Using typescript@1.8.10 and /Users/giksa/Varios/consulta/conf/ts.conf.json
[22:13:57] Time: 6067ms
   Asset    Size  Chunks       Chunk Names
index.js  5.5 MB       0       main

ERROR in ./src/app/techs/techs.ts
(2,24): error TS2307: Cannot find module 'axios'.

ERROR in ./src/index.ts
(8,25): error TS2307: Cannot find module 'angular2/bootstrap'.

ERROR in ./src/index.ts
(1,1): error TS6053: File '/Users/giksa/Varios/consulta/typings/main.d.ts' not found.

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'angular2/bootstrap' in '/Users/giksa/Varios/consulta/src'
 @ ./src/index.ts 7:18-47
```

**Comment by micaelmbagira** [comment]
Can you give the version you are using and which framework/language/modules ?

**Comment by giksa** [comment]
`npm i -g generator-fountain-webapp` output:

```
~/V/consulta » npm i -g generator-fountain-webapp
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
/usr/local/lib
└── generator-fountain-webapp@0.4.0
```

`npm ls -g --depth 0` output:

```
~/V/consulta » npm ls -g --depth 0
/usr/local/lib
├── bower@1.7.9
├── generator-fountain-webapp@0.4.0
├── gulp-cli@1.2.1
├── npm@3.8.9
└── yo@1.8.3
```

`yo doctor` output:

```
~/V/consulta » yo doctor
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
```

```
❯ yo fountain-webapp
? Which JavaScript framework do you want? Angular 2
? Which module management do you want? Webpack with NPM
? Which CSS preprocessor do you want? SASS
? Which JS preprocessor do you want? Typescrypt
? Do you want a sample app? A working landing page
```

OS: OSX Capitan (10.11.4)
Node Version: v6.2.0
npm version: 3.8.9

**Comment by Swiip** [comment]
released, can you confirm it's ok?

**Comment by kikar** [comment]
With this configuration, working until end of `npm install`:

```
node v6.2.0
npm 3.8.9
? Which JavaScript framework do you want? Angular 2
? Which module management do you want? Webpack with NPM
? Which JS preprocessor do you want? TypeScript
? Which CSS preprocessor do you want? SASS
? Do you want a sample app? A working landing page
```

Then I get this error on `gulp serve`:

```
/Users/home/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/home/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by zckrs** [comment]
Can you use `npm run serve` ?

**Comment by kikar** [comment]
Yep @zckrs, that works!

**Comment by kikar** [comment]
With this configuration, fails at `npm install`:

```
node 4.4.5
npm 2.15.5
? Which JavaScript framework do you want? Angular 2
? Which module management do you want? Webpack with NPM
? Which JS preprocessor do you want? TypeScript
? Which CSS preprocessor do you want? SASS
? Do you want a sample app? A working landing page
```

I get this error:

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/home/.nvm/versions/node/v4.4.5/bin/node" "/Users/home/.nvm/versions/node/v4.4.5/bin/npm" "i"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.0.0-rc.1 wants rxjs@5.0.0-beta.6
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.1 wants rxjs@5.0.0-beta.6

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/home/Desktop/prova/npm-debug.log
```

**Comment by zckrs** [comment]
If you want use gulp directly you should `npm i -g gulp-cli` instead of `npm i -g gulp`

**Comment by zckrs** [comment]
http://fountainjs.io/doc/usage/#requirements

npm 2 issue :-(

**Comment by kikar** [comment]
Oh sorry, missed that info. Anyway default for 4.x is npm 2, so maybe you should require at least Node 5.x, or make it clearer that it requires npm 3

**Comment by kikar** [comment]
Also, sorry for the small OT, but I've just realised I missed the whole Documentation page, cause on Safari Technology Preview 4 appears as an empty page. Works fine with Safari and Chrome.

**Comment by Swiip** [comment]
Sorry for the "not helping troll" but i just tried with Safari Technology Preview and I got `ReferenceError: Can't find variable: fetch`... Will try to fix that... (workaround: just reload the page on the doc url)

**Comment by Swiip** [comment]
I added the fetch polyfill on the website, should work now.

**Comment by zckrs** [comment]
Can we close issue @kikar?

**Comment by kikar** [comment]
Good for me, thanks!
