### ISSUE TITLE
yo fountain-webapp -> throw er;

### ISSUE THREAD

**Issue by bArraxas** [FountainJS/generator-fountain-webapp#207]
Hi,

I can't run the command line "yo fountain-webapp".

I had tryed all those configs : 
- yo: 1.5, 2.0
- npm: 3, 4, 5
- node: 4, 5, 6, 7, 8

Can you help me please ?
Regards,

### Error Message & Stack Trace

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at child.Base.prompt (C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\yeoman-generator\lib\index.js:168:45)
    at child.fountainPrompting (C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\fountain-generator\lib\Base.js:109:17)
    at child.prompting (C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\generators\app\index.js:15:17)
    at Object.<anonymous> (C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\yeoman-generator\lib\index.js:417:23)
    at C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\run-async\index.js:25:25
    at C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\run-async\index.js:24:19
    at C:\Users\ac39\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\yeoman-generator\lib\index.js:418:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

### Config
{ "generator-generator": {} }

## Environment (actuel)
Node.js v6.11.0
win32 6.1.7601 (but i use a window 64bit)
yo --version : 1.5
npm --version : 5.0.3

**Comment by valentinpeluso92** [comment]
I have the same problem
