### ISSUE TITLE
build: SystemJS and build static

### ISSUE THREAD

**Issue by wojciechpolak** [FountainJS/generator-fountain-webapp#23]
Regarding the recent code change in `gulp_tasks/systemjs.js`:

1) When using `const Builder = require('jspm').Builder`

`serve` works with Chrome (but not FF), and `serve:dist` fails with "Uncaught Module 1 not present." in a browser console.

2) When using `const Builder = require('systemjs-builder');`

`serve` same as above, and `serve:dist` fails during build:

```
[15:34:55] Finished 'styles' after 2.41 s
[15:34:55] 'systemjs' errored after 2.9 s
[15:34:55] TypeError: No resolution found at all for condition github:jspm/nodelibs-process@0.2.0-alpha/#:./process.js.
    at [project-path]/node_modules/systemjs-builder/lib/trace.js:683:15
    at Array.forEach (native)
    at [project-path]/node_modules/systemjs-builder/lib/trace.js:676:6
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher ([project-path]/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ([project-path]/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise ([project-path]/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 ([project-path]/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises ([project-path]/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue ([project-path]/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues ([project-path]/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] ([project-path]/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

versions: jspm 0.17.0-beta.13, systemjs-builder 0.15.15, systemjs 0.19.26

**Comment by Swiip** [comment]
Versions has been upgraded in last 0.5 release. It should be ok now.
