### ISSUE TITLE
Test configuration does not work for Angular 1 typescript

### ISSUE THREAD

**Issue by prbaron** [FountainJS/generator-fountain-webapp#34]
Hello, 

I created a project with Angular1, Typescript, webpack and SCSS.

I ran `npm install` and `typings install`.

When I run `gulp test`, I have the following errors : 

```
[17:27:13] Loading /Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/misc.js
[17:27:13] Loading /Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/browsersync.js
[17:27:13] Loading /Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/karma.js
[17:27:13] Loading /Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/webpack.js
[17:27:14] Loading /Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/partials.js
[17:27:14] Using gulpfile ~/Sites/generator-fountain-webapp/gulpfile.js
[17:27:14] Starting 'test'...
[17:27:14] Starting 'karma:single-run'...
24 05 2016 17:27:14.600:WARN [preprocess]: Can not load "webpack"!
  Error: Passed 'options' object don't look like a valid webpack configuration
    at webpack (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/webpack/lib/webpack.js:19:10)
    at new Plugin (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma-webpack/index.js:50:17)
    at invoke (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:59:20)
    at get (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:48:43)
    at /Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:70:31)
    at get (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma/lib/preprocessor.js:52:20)
    at Array.forEach (native)
    at /Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma/lib/preprocessor.js:68:21
    at Array.forEach (native)
    at createPreprocessor (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma/lib/preprocessor.js:67:12)
    at Array.invoke (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:75:15)
    at get (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:48:43)
    at /Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at invoke (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/di/lib/injector.js:70:31)
    at Server.start (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma/lib/server.js:102:18)
    at karmaSingleRun (/Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/karma.js:18:15)
    at taskWrapper (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/undertaker/lib/set-task.js:13:15)
24 05 2016 17:27:14.660:WARN [karma]: Port 9876 in use
24 05 2016 17:27:14.661:INFO [karma]: Karma v0.13.22 server started at http://localhost:9877/
24 05 2016 17:27:14.664:INFO [launcher]: Starting browser PhantomJS
24 05 2016 17:27:15.421:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#6l6bqkbkFEd49AIRAAAA with id 42625276
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/index.spec.js:3


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/app/footer.html.js:1


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/app/header.html.js:1


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/app/main.html.js:1


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/app/techs/tech.html.js:1


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/app/techs/techs.html.js:1


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/app/title.html.js:1


PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/pierrebaron/Sites/generator-fountain-webapp/src/index.html.js:1


[17:27:15] 'karma:single-run' errored after 1.18 s
[17:27:15] Error: Failed 1 tests.
    at /Users/pierrebaron/Sites/generator-fountain-webapp/gulp_tasks/karma.js:11:22
    at removeAllListeners (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/Users/pierrebaron/Sites/generator-fountain-webapp/node_modules/karma/lib/server.js:347:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickDomainCallback (node.js:394:17)
[17:27:15] 'test' errored after 1.18 s
```

**Comment by Swiip** [comment]
Can you check with the last 0.5 version ?

**Comment by prbaron** [comment]
It works indeed with 0.5 version. I now have to understand why it is not working with ngForward. Thanks !

**Comment by mattarau** [comment]
Hey @Swiip,

Would you mind pointing what were the changes to fix this? I already have a project with this issue and it's not possible to generate again over it. So I think I'll have to manually fix it.

Cheers!

**Comment by micaelmbagira** [comment]
Hi, actually I don't know. At the time this issue was created, the issue was already fixed...
You could generate another project and then copy/paste your `src/` in the new project.

**Comment by mattarau** [comment]
@micaelmbagira Sorry for the delay...  I actually have it fixed in the project already and can't remember how, but since it's already fixed here, then it's ok... Thanks!
