### ISSUE TITLE
Gulp serve error

### ISSUE THREAD

**Issue by drixie** [FountainJS/generator-fountain-webapp#53]
```
$ gulp serve
[13:01:14] Loading gulp_tasks\browsersync.js
[13:01:14] Loading gulp_tasks\build.js
[13:01:16] Loading gulp_tasks\inject.js
[13:01:17] Loading gulp_tasks\karma.js
[13:01:18] Loading gulp_tasks\misc.js
[13:01:18] Loading gulp_tasks\partials.js
[13:01:18] Loading gulp_tasks\scripts.js
[13:01:19] Loading gulp_tasks\styles.js
[13:01:19] Using gulpfile ~\{PROJECT DIRECTORY}\gulpfile.js
C:\Users\roverbot\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\roverbot\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by zckrs** [comment]
We use Gulp4 you should:
- use `npm run serve`
  OR
- install gulp-cli instead of gulp in global (`npm r -g gulp && npm i -g gulp-cli`)

**Comment by ChuckkNorris** [comment]
@zckrs Why does running `npm run serve` instead of `gulp serve` resolve this issue?
NPM just runs `gulp serve` anyways as defined in the `package.json` file, no?
