### ISSUE TITLE
ES6 Spread operator

### ISSUE THREAD

**Issue by raphael22** [FountainJS/generator-fountain-webapp#76]
## Description

Can't use ES6 spread operator on object.
Tried on a fresh hello project.

``` javascript
const DEFAULT_MODEL  = {
  user:null
}
this.model = { ...DEFAULT_MODEL  } /!\
```
### Error Message & Stack Trace

```
ERROR in ./src/index.js
Module build failed: SyntaxError: /media/nikopol/DATA/www/test-fountain/fountain-angular-1/src/index.js: Unexpected token (20:15)
  18 |   user:null
  19 | }
> 20 | this.model = { ...DEFAULT_MODEL  } 
     |                ^
    at Parser.pp.raise (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseIdentifier (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:1067:10)
    at Parser.pp.parsePropertyName (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:872:117)
    at Parser.pp.parseObj (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:788:12)
    at Parser.pp.parseExprAtom (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:491:19)
    at Parser.pp.parseExprSubscripts (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:277:19)
    at Parser.pp.parseMaybeUnary (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:257:19)
    at Parser.pp.parseExprOps (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:188:19)
    at Parser.pp.parseMaybeConditional (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseMaybeAssign (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:151:23)
    at Parser.pp.parseExpression (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/expression.js:92:19)
    at Parser.pp.parseStatement (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/statement.js:163:19)
    at Parser.pp.parseBlockBody (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/parser/index.js:129:19)
    at parse (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babylon/lib/index.js:47:47)
    at File.parse (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/index.js:517:34)
    at File.parseCode (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/index.js:603:20)
    at /media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/index.js:563:16)

```
### Config

``` json
{
  "generator-fountain-angular1": {
    "version": "0.6.0",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "babel",
      "css": "scss",
      "resolved": "/usr/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular1/generators/app/index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "hello",
      "router": "uirouter"
    }
  }
}
```
## Environment

```
Node.js v6.3.0
linux 4.4.0-28-generic
yo 1.8.4
npm 3.10.3
```

**Comment by micaelmbagira** [comment]
Hi, @raphael22 this is related to babel, not FountainJS: https://babeljs.io/docs/plugins/transform-object-rest-spread/

**Comment by raphael22** [comment]
But all is set to use it.
My .babelrc

``` json
{
  "presets": [
    "es2015"
  ]
}
```

And the webpack loader.

```
{
    test: /\.js$/,
    exclude: /node_modules\/((?!zetapush))/,
    loaders: [
      'ng-annotate',
      'babel?plugins[]=transform-inline-environment-variables'
    ]
}
```

**Comment by micaelmbagira** [comment]
No, you need to add `transform-object-rest-spread` to your `.babelrc`: https://babeljs.io/docs/plugins/transform-object-rest-spread/

**Comment by raphael22** [comment]
Preset 2015 aren't supposed to include it ?
https://babeljs.io/docs/plugins/preset-es2015/

**Comment by raphael22** [comment]
Now this babel config : 

``` json
{
  "presets": [
    "es2015"
  ],
  "plugins": ["transform-object-rest-spread"]
}
```

give me this error despite that the package is installed on a hello sample : 

```
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/media/nikopol/DATA/www/test-fountain/fountain-angular-1/.babelrc" at 0, attempted to resolve relative to "/media/nikopol/DATA/www/test-fountain/fountain-angular-1"
    at /media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/media/nikopol/DATA/www/test-fountain/fountain-angular-1/node_modules/babel-loader/index.js:88:12)
```

**Comment by micaelmbagira** [comment]
- preset-es2015 includes `spread` but not `rest`, this is a bit different: https://babeljs.io/docs/plugins/transform-object-rest-spread/
- Plus, you need to **install** the plugin from npm, please read https://babeljs.io/docs/plugins/transform-object-rest-spread/. Everything is explained.

**Comment by raphael22** [comment]
Oh yes, spread not rest-spread, my bad.
Thanks !

**Comment by elderbas** [comment]
What's the opinion for including babel plugins like these in the build? Or is it something people should be expected to install on their own so it's more optional?

**Comment by micaelmbagira** [comment]
@elderbas as we provide minimalist models, we usually don't need those plugins so we don't provide them and users should install them by their own. Though, for https://github.com/FountainJS/generator-fountain-vue we use the rest and spread quite often so we included this plugin in the default configuration.
