### ISSUE TITLE
Error: File not found with singular glob

### ISSUE THREAD

**Issue by musakarakas** [FountainJS/generator-fountain-webapp#92]
## Description

Changing paths.src to a subdirectory causes build error.
`npm run serve` works, but `npm run build` fails.

This path in the error message is incorrect:
`C:\workspace\yo\fountain\bower_components\todomvc-app-css\index.css`
The file is actually located at:
C:\workspace\yo\fountain\bower-inject-js\bower_components\todomvc-app-css\index.css`
### Error Message & Stack Trace

```
[20:22:56] Finished 'inject' after 1.86 s
[20:22:56] Starting 'build'...
[20:22:56] gulp-inject 1 files into index.html.
[20:22:56] 'build' errored after 103 ms
[20:22:56] Error: Error: File not found with singular glob: C:\workspace\yo\fountain\bower_components\todomvc-app-css\index.css
    at DestroyableTransform.<anonymous> (C:\workspace\yo\fountain\bower-inject-js\node_modules\gulp-useref\lib\streamManager.js:90:36)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at Glob.<anonymous> (C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\index.js:38:16)
    at Glob.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\node_modules\glob\glob.js:172:8)
    at done (C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\node_modules\glob\glob.js:159:12)
    at Glob._processSimple2 (C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\node_modules\glob\glob.js:652:12)
    at C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\node_modules\glob\glob.js:640:10
    at Glob._stat2 (C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\node_modules\glob\glob.js:736:12)
    at lstatcb_ (C:\workspace\yo\fountain\bower-inject-js\node_modules\glob-stream\node_modules\glob\glob.js:728:12)
    at RES (C:\workspace\yo\fountain\bower-inject-js\node_modules\inflight\inflight.js:23:14)
[20:22:56] 'build' errored after 2.08 s
[20:22:56] 'default' errored after 2.13 s
```
### Config

Copy the content from `.yo-rc.json`:

``` json
{
  "generator-fountain-angular1": {
    "version": "0.6.0",
    "props": {
      "framework": "angular1",
      "modules": "inject",
      "js": "js",
      "css": "css",
      "resolved": "C:\\Users\\musa.karakas\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-webapp\\node_modules\\generator-fountain-angular1\\generators\\app\\index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "todoMVC",
      "router": "none"
    }
  }
}
```
## Relevant Links

https://github.com/musakarakas/fountain-nested-paths-src
## Environment

``` bash
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v6.3.0
win32 6.2.9200

yo --version
1.8.4

npm --version
3.10.3
```

**Comment by micaelmbagira** [comment]
Hi @musakarakas As you moved `src/` to `x/src`, when gulp injects css in `index.html`, it goes **2** levels up so `<link rel="stylesheet" href="../../bower_components/todomvc-app-css/index.css" />`. Consequently, in `.tmp/index.html`,  this path is wrong. So I think you should move `src` out of `x` or handle the problem manually, with gulp tasks maybe...

**Comment by musakarakas** [comment]
Now I understand. It's about the inject task.
Replacing src with x/src in index.html fixed the problem.
`<!-- build:css({.tmp,x/src}) styles/vendor.css -->`

Thanks
